networks:
  nexus:
    external: true
services:
  dozzle:
    cap_drop:
      - ALL
    container_name: dozzle
    depends_on:
      docker-socket-proxy:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 32M
    environment:
      DOCKER_HOST: tcp://docker-socket-proxy:2375
      DOZZLE_LEVEL: info
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "/dozzle", "healthcheck" ]
      timeout: 10s
    hostname: dozzle
    image: amir20/dozzle
    labels:
      homepage.description: Real-time Container Logs
      homepage.group: Observability
      homepage.href: https://dozzle.${DOMAIN:?DOMAIN not set}
      homepage.icon: dozzle
      homepage.name: Dozzle
    networks:
      - nexus
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "${PUID:?PUID not set}:${PGID:?PGID not set}"
