services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    hostname: whoami
    user: "1000:1000"
    healthcheck:
      test: ["NONE"]
    labels:
      homepage.group: Utilities
      homepage.name: Whoami
      homepage.icon: traefik
      homepage.description: Request Debug Service
      homepage.href: https://whoami.${DOMAIN}
      traefik.http.services.whoami.loadbalancer.server.port: 80
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
        reservations:
          cpus: '0.01'
          memory: 8M
    restart: unless-stopped
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=8m
    networks:
      - nexus

networks:
  nexus:
    external: true
