networks:
  nexus:
    external: true
services:
  whoami:
    container_name: whoami
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
        reservations:
          cpus: '0.01'
          memory: 8M
    healthcheck:
      test: [ "NONE" ]
    hostname: whoami
    image: traefik/whoami
    labels:
      homepage.description: Request Debug Service
      homepage.group: Utilities
      homepage.href: https://whoami.${DOMAIN:?DOMAIN not set}
      homepage.icon: traefik
      homepage.name: Whoami
    networks:
      - nexus
    restart: unless-stopped
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=8m
    user: "${PUID:?PUID not set}:${PGID:?PGID not set}"
