networks:
  nexus:
    external: true
services:
  plex-exporter:
    cap_drop:
      - ALL
    container_name: plex-exporter
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 16M
    environment:
      PLEX_SERVER: ${PLEX_SERVER_URL:?PLEX_SERVER_URL not set}
      PLEX_TOKEN: ${PLEX_TOKEN:?PLEX_TOKEN not set}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 15s
      test: [ "NONE" ]
      timeout: 10s
    hostname: plex-exporter
    image: ghcr.io/timothystewart6/prometheus-plex-exporter
    labels:
      homepage.description: Plex Metrics Exporter
      homepage.group: Observability
      homepage.icon: prometheus
      homepage.name: Plex Exporter
      traefik.enable: false
    networks:
      - nexus
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "65534:65534"
