services:
  beszel-agent:
    cap_add:
      - CAP_PERFMON
    cap_drop:
      - ALL
    container_name: beszel-agent
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 16M
    devices:
      - /dev/dri/card0
    environment:
      HUB_URL: ${BESZEL_HUB_URL:?BESZEL_HUB_URL not set}
      KEY: ${BESZEL_KEY:?BESZEL_KEY not set}
      LISTEN: ${BESZEL_LISTEN:?BESZEL_LISTEN not set}
      TOKEN: ${BESZEL_TOKEN:?BESZEL_TOKEN not set}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 15s
      test: [ "NONE" ]
      timeout: 10s
    hostname: beszel-agent
    image: henrygd/beszel-agent-intel
    labels:
      homepage.description: Server Monitoring Agent
      homepage.group: Observability
      homepage.icon: beszel
      homepage.name: Beszel Agent
      traefik.enable: false
    network_mode: host
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/var/lib/beszel-agent
