networks:
  nexus:
    external: true
services:
  unpackerr:
    cap_drop:
      - ALL
    container_name: unpackerr
    depends_on:
      lidarr:
        condition: service_healthy
      radarr:
        condition: service_healthy
      sonarr:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 64M
    environment:
      TZ: ${TZ:?TZ not set}
      UN_LIDARR_0_API_KEY: ${LIDARR_API_KEY:?LIDARR_API_KEY not set}
      UN_LIDARR_0_URL: http://lidarr:8686
      UN_RADARR_0_API_KEY: ${RADARR_API_KEY:?RADARR_API_KEY not set}
      UN_RADARR_0_URL: http://radarr:7878
      UN_SONARR_0_API_KEY: ${SONARR_API_KEY:?SONARR_API_KEY not set}
      UN_SONARR_0_URL: http://sonarr:8989
    healthcheck:
      test: [ "NONE" ]
    hostname: unpackerr
    image: ghcr.io/unpackerr/unpackerr
    labels:
      homepage.description: Archive Extractor for *arr Apps
      homepage.group: Curation
      homepage.icon: unpackerr
      homepage.name: Unpackerr
      traefik.enable: false
    networks:
      - nexus
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
    user: "${PUID:?PUID not set}:${PGID:?PGID not set}"
    volumes:
      - ${MEDIA_PATH:?MEDIA_PATH not set}/downloads:/downloads
