networks:
  nexus:
    external: true
services:
  wizarr:
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    container_name: wizarr
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.05'
          memory: 128M
    environment:
      TZ: ${TZ:?TZ not set}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD-SHELL", "curl -f http://localhost:5690 || exit 1" ]
      timeout: 10s
    hostname: wizarr
    image: ghcr.io/wizarrrr/wizarr
    labels:
      homepage.description: Media Server Invitation System
      homepage.group: Media
      homepage.href: https://wizarr.${DOMAIN:?DOMAIN not set}
      homepage.icon: wizarr
      homepage.name: Wizarr
    networks:
      - nexus
    ports:
      - 5690:5690
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
    volumes:
      - ./database:/data/database
      - ./wizard_steps:/data/wizard_steps
