networks:
  nexus:
    external: true
services:
  garage:
    cap_drop:
      - ALL
    container_name: garage
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      TZ: ${TZ:?TZ not set}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "NONE" ]
      timeout: 10s
    hostname: garage
    image: dxflrs/garage:v2.1.0
    labels:
      homepage.description: S3-compatible Object Storage
      homepage.group: Storage
      homepage.icon: minio
      homepage.name: Garage
      traefik.enable: false
    networks:
      - nexus
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=128m
    user: "${PUID:?PUID not set}:${PGID:?PGID not set}"
    volumes:
      - ./config/garage.toml:/etc/garage.toml:ro
      - ./meta:/var/lib/garage/meta
      - ./data:/var/lib/garage/data
