services:
  kromgo:
    image: ghcr.io/kashalls/kromgo
    container_name: kromgo
    hostname: kromgo
    user: "65532:65532"
    depends_on:
      prometheus:
        condition: service_healthy
    environment:
      PROMETHEUS_URL: ${PROMETHEUS_URL:?PROMETHEUS_URL not set}
    healthcheck:
      test: ["NONE"]
    labels:
      homepage.group: Observability
      homepage.name: Kromgo
      homepage.icon: prometheus
      homepage.description: Prometheus Badge Generator
      homepage.href: https://kromgo.${DOMAIN:?DOMAIN not set}
      traefik.http.routers.kromgo.rule: Host(`kromgo.${DOMAIN:?DOMAIN not set}`) || Host(`stat.${DOMAIN:?DOMAIN not set}`)
    ports:
      - 8082:8080
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 16M
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    volumes:
      - ./data/kromgo.yaml:/kromgo/config.yaml:ro
    networks:
      - nexus
networks:
  nexus:
    external: true
