services:
  loki:
    image: grafana/loki
    container_name: loki
    hostname: loki
    user: "1000:1000"
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: ["NONE"]
    labels:
      homepage.group: Observability
      homepage.name: Loki
      homepage.icon: loki
      homepage.description: Log Aggregation
      traefik.enable: "false"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
    volumes:
      - ${DATA_PATH}/loki:/loki
    networks:
      - nexus

networks:
  nexus:
    external: true
