networks:
  nexus:
    external: true
services:
  trala:
    cap_drop:
      - ALL
    container_name: trala
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 32M
    environment:
      LOG_LEVEL: info
      REFRESH_INTERVAL_SECONDS: "30"
      SEARCH_ENGINE_URL: "https://duckduckgo.com/?q:"
      TRAEFIK_API_HOST: http://traefik:8080
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8080 || exit 1" ]
      timeout: 10s
    hostname: trala
    image: ghcr.io/dannybouwers/trala
    labels:
      homepage.description: Traefik Service Discovery Dashboard
      homepage.group: Dashboard
      homepage.href: https://trala.${DOMAIN:?DOMAIN not set}
      homepage.icon: traefik
      homepage.name: Trala
    networks:
      - nexus
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=32m
    user: "${PUID:?PUID not set}:${PGID:?PGID not set}"
    volumes:
      - ./data:/config:ro
